/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    container: { center: true, padding: '2rem', screens: { '2xl': '1400px' } },
    extend: {
      colors: {
        border: '#d7c2ba',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#feb696',
        'on-primary-container': '#d99577',
        'on-secondary-fixed': '#261900',
        'on-primary-fixed': '#351000',
        'surface-container-low': '#fef1ed',
        'surface-variant': '#ece0dc',
        'on-tertiary-container': '#7aaeb6',
        'on-secondary-fixed-variant': '#5d4201',
        'background': '#fff8f6',
        'primary': '#421904',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'velvet-red': '#A82024',
        'on-error-container': '#93000a',
        'mahogany-dark': '#3D1F10',
        'on-surface': '#201a18',
        'primary-fixed': '#ffdbcc',
        'primary-container': '#5d2e17',
        'tertiary': '#002a2f',
        'on-primary': '#ffffff',
        'brass-highlight': '#E8D09B',
        'on-tertiary-fixed-variant': '#144e55',
        'on-tertiary-fixed': '#001f23',
        'secondary-fixed-dim': '#e9c176',
        'error': '#ba1a1a',
        'surface-dim': '#e4d8d3',
        'surface-tint': '#885037',
        'outline': '#85736d',
        'on-background': '#201a18',
        'inverse-surface': '#362f2c',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed488',
        'tertiary-fixed': '#b6ecf4',
        'surface': '#fff8f6',
        'tertiary-fixed-dim': '#9bcfd8',
        'tertiary-container': '#004249',
        'sheet-cream': '#FDFBF7',
        'on-error': '#ffffff',
        'surface-container-highest': '#ece0dc',
        'on-primary-fixed-variant': '#6b3922',
        'secondary': '#775a19',
        'on-surface-variant': '#52443e',
        'inverse-primary': '#feb696',
        'surface-container': '#f8ebe7',
        'secondary-fixed': '#ffdea5',
        'inverse-on-surface': '#fbeeea',
        'surface-container-high': '#f2e6e1',
        'on-secondary-container': '#785a1a',
        'surface-bright': '#fff8f6',
        'outline-variant': '#d7c2ba',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      spacing: {
        'stack-lg': '48px',
        gutter: '16px',
        'stack-md': '24px',
        'stack-sm': '12px',
        'container-padding': '24px',
        unit: '8px',
      },
      fontFamily: {
        'label-caps': ['Hanken Grotesk'],
        'headline-lg': ['EB Garamond'],
        'title-md': ['Hanken Grotesk'],
        'headline-lg-mobile': ['EB Garamond'],
        'display-lg': ['EB Garamond'],
        'body-lg': ['Hanken Grotesk'],
        'body-sm': ['Hanken Grotesk'],
        display: ['"EB Garamond"', 'Georgia', 'serif'],
        heading: ['"EB Garamond"', 'Georgia', 'serif'],
        body: ['"Hanken Grotesk"', 'system-ui', 'sans-serif'],
        sans: ['"Hanken Grotesk"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      keyframes: {
        'pop-in': { '0%': { transform: 'scale(0.9)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'slide-up': { '0%': { transform: 'translateY(8px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        'wiggle': {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(-12deg)' },
          '75%': { transform: 'rotate(12deg)' },
        },
        'bounce-in': {
          '0%': { transform: 'scale(0)' },
          '50%': { transform: 'scale(1.15)' },
          '100%': { transform: 'scale(1)' },
        },
        'wrong-shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-6px)' },
          '40%': { transform: 'translateX(6px)' },
          '60%': { transform: 'translateX(-4px)' },
          '80%': { transform: 'translateX(4px)' },
        },
      },
      animation: {
        'pop-in': 'pop-in 0.3s ease-out',
        'slide-up': 'slide-up 0.3s ease-out',
        'wiggle': 'wiggle 0.5s ease-in-out',
        'bounce-in': 'bounce-in 0.5s ease-out',
        'wrong-shake': 'wrong-shake 0.5s ease-in-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
